services:
  arti:
    image: arti:latest
    hostname: arti
    container_name: arti_with_bridges
    ports:
      - "9150:9150"
    environment:
      - "NUM_RELAYS=100"
      - "MIN_RELAYS=1"
      - "RELAY_TIMEOUT=3"