services:
  arti:
    image: deathmond1987/arti-tor-bridges:latest
    hostname: arti
    container_name: arti_with_bridges
    ports:
      - "9150:9150"
    environment:
      - "NUM_RELAYS=200"
      - "MIN_RELAYS=3"
      - "RELAY_TIMEOUT=4"
      - "SOCKS_LISTEN=9150"
    cap_add:
      - NET_ADMIN
    network_mode: "host"
